a=0
try: # try used to find exception
    c = 1/a
    print(c)
except Exception as e: # to handle the exception
    print(e)
